# Generated by Django 3.1.7 on 2021-02-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210220_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskRow',
            new_name='TaskColumn',
        ),
    ]
