# Generated by Django 3.1.7 on 2021-02-20 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0004_auto_20210220_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcolumn',
            name='owner',
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
